name: migration
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.12
    - numpy>=2.0
    - pandas
    - matplotlib
    - tqdm
    - astropy
    - jupyterlab
    - scipy
    - pip
    - pip:
        - vice>=1.3.1
        - dill
